settings:
  title: 'Status Page'
  url: 'https://status.mlsub.net' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: mlsub-net # unique identifier
    name: 梦蓝发布站
    description: 'Home page' # default=empty
    url: 'https://mlsub.net/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: wx-api-backend
    name: 微信 API
    description: ''
    url: 'https://api.suisuichan.net/wechat.php?vid=wxv_1546636550262882305'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
    
  - id: weibo-api-backend
    name: 微博 API
    description: ''
    url: 'https://api.suisuichan.net/weibo/?id=1034:4690428122038301'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
    
  - id: centurylink-api-backend
    name: OneDrive API
    description: ''
    url: 'https://od.mlsub.net/v/1.mp4'
    method: GET
    expectStatus: 302
    linkable: false # allows the title to be a link, default=true
    
  - id: fallback-source
    name: 备用视频源
    description: ''
    url: 'https://v.mlsub.net/1.mp4'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
